# ==========================================================
# Application
# ==========================================================
spring.application.name=back-end-test

# ==========================================================
# JPA / Hibernate
# ==========================================================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ==========================================================
# Logging
# ==========================================================
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

# ==========================================================
# Security
# ==========================================================
jwt.secret=grbZEglJkh+v8ArnoS2VXtIShtoc/4BEqYQI/S4SN5M=

# ==========================================================
# Disable seeders
# ==========================================================
admin.seed.enabled=false
