name: Lint Dockerfiles

on:
  push:
  pull_request:

jobs:
  dockerlint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./app/Dockerfile
